require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DataFeedsController do

  # This should return the minimal set of attributes required to create a valid
  # DataFeed. As you add validations to DataFeed, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "merchant_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DataFeedsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all data_feeds as @data_feeds" do
      data_feed = DataFeed.create! valid_attributes
      get :index, {}, valid_session
      assigns(:data_feeds).should eq([data_feed])
    end
  end

  describe "GET show" do
    it "assigns the requested data_feed as @data_feed" do
      data_feed = DataFeed.create! valid_attributes
      get :show, {:id => data_feed.to_param}, valid_session
      assigns(:data_feed).should eq(data_feed)
    end
  end

  describe "GET new" do
    it "assigns a new data_feed as @data_feed" do
      get :new, {}, valid_session
      assigns(:data_feed).should be_a_new(DataFeed)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_feed as @data_feed" do
      data_feed = DataFeed.create! valid_attributes
      get :edit, {:id => data_feed.to_param}, valid_session
      assigns(:data_feed).should eq(data_feed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DataFeed" do
        expect {
          post :create, {:data_feed => valid_attributes}, valid_session
        }.to change(DataFeed, :count).by(1)
      end

      it "assigns a newly created data_feed as @data_feed" do
        post :create, {:data_feed => valid_attributes}, valid_session
        assigns(:data_feed).should be_a(DataFeed)
        assigns(:data_feed).should be_persisted
      end

      it "redirects to the created data_feed" do
        post :create, {:data_feed => valid_attributes}, valid_session
        response.should redirect_to(DataFeed.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_feed as @data_feed" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataFeed.any_instance.stub(:save).and_return(false)
        post :create, {:data_feed => { "merchant_id" => "invalid value" }}, valid_session
        assigns(:data_feed).should be_a_new(DataFeed)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataFeed.any_instance.stub(:save).and_return(false)
        post :create, {:data_feed => { "merchant_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested data_feed" do
        data_feed = DataFeed.create! valid_attributes
        # Assuming there are no other data_feeds in the database, this
        # specifies that the DataFeed created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DataFeed.any_instance.should_receive(:update).with({ "merchant_id" => "1" })
        put :update, {:id => data_feed.to_param, :data_feed => { "merchant_id" => "1" }}, valid_session
      end

      it "assigns the requested data_feed as @data_feed" do
        data_feed = DataFeed.create! valid_attributes
        put :update, {:id => data_feed.to_param, :data_feed => valid_attributes}, valid_session
        assigns(:data_feed).should eq(data_feed)
      end

      it "redirects to the data_feed" do
        data_feed = DataFeed.create! valid_attributes
        put :update, {:id => data_feed.to_param, :data_feed => valid_attributes}, valid_session
        response.should redirect_to(data_feed)
      end
    end

    describe "with invalid params" do
      it "assigns the data_feed as @data_feed" do
        data_feed = DataFeed.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataFeed.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_feed.to_param, :data_feed => { "merchant_id" => "invalid value" }}, valid_session
        assigns(:data_feed).should eq(data_feed)
      end

      it "re-renders the 'edit' template" do
        data_feed = DataFeed.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataFeed.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_feed.to_param, :data_feed => { "merchant_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_feed" do
      data_feed = DataFeed.create! valid_attributes
      expect {
        delete :destroy, {:id => data_feed.to_param}, valid_session
      }.to change(DataFeed, :count).by(-1)
    end

    it "redirects to the data_feeds list" do
      data_feed = DataFeed.create! valid_attributes
      delete :destroy, {:id => data_feed.to_param}, valid_session
      response.should redirect_to(data_feeds_url)
    end
  end

end
